name: Deploy Single-File App to Azure

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event.name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    permissions:
      id-token: write # Required for secure OIDC authentication
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # No build steps are needed for a simple HTML file!

      - name: Deploy to Azure Static Web Apps
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          # This action uses OIDC authentication automatically because of the 'permissions' block above
          action: "upload"

          ###### App Configurations ######
          # For a single file in your root directory, these are the correct settings.
          app_location: "/"  # Your app code is in the root directory.
          api_location: ""   # No API.
          output_location: "" # No build output folder, so leave this blank.
          ###### End of Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    permissions:
      id-token: write # Also required here to close the staging environment
    steps:
      - name: Close Pull Request Staging Environment
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: "close"
